services:
  - type: web
    name: homebaise-bot
    env: node
    rootDir: bot
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HOMEBASE_API_URL
        sync: false
      - key: BOT_SERVER_TOKEN
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: BOT_SKIP_DB
        value: "false"

